### ISSUE TITLE
poprawki

### ISSUE THREAD

**Issue by zdolny** [tomsloni/kodilla-papier#2]
1. usun console.log z kodu
2. do warunkow zakonczenia gry dodaj opcje remisu (czyli sytuacja kiedy jest 9:9 i wypadnie remis).
Mozesz to przetestowac w konsoli przegladarki np tak:
`player.score = 10;`
`computer.score = 10;`
`setGamePoints();`
`checkRoundWinner();`

**Comment by tomsloni** [comment]
Wcześniej gra nie przyznawała punktów za remis, ale do tego ćwiczenia dodałem.
Potem zczaiłem, że w sumie nie musiałem i mogłem dodać martwą opcję wywołania ostatecznego wyniku remisu, która nie wystąpi w rzeczywistości, ale można ją wywołać z poziomu konsoli. No ale już zrobiłem jak zrobiłem. :D

**Comment by zdolny** [comment]
faktycznie, sorry Tomek, cos sobie ubzduralem z tym remisem, propsy za rozkmine i rozwiazanie
